---
title: "`bit::vector` --- Overwrites"
---

{{< include /pages/_common.qmd >}}

A bit-vector can be overwritten with bits sourced from an unsigned word, a collection of unsigned words, or a `std::bitset`:

```cpp
template<std::unsigned_integral Src=>
constexpr vector& set_to(Src src);                          // <1>

template<typename Iter>
constexpr vector& set_to(Iter b, Iter e);                   // <2>

template<std::unsigned_integral Src>
constexpr vector& set_to(std::initializer_list<Src> src);   // <3>

template<std::unsigned_integral Src>
constexpr vector& set_to(const std::vector<Src> &src);      // <4>

template<std::unsigned_integral Src, std::size_t N>
constexpr vector& set_to(const std::array<Src,N> &src);     // <5>

template<std::size_t N>
constexpr vector& set_to(const std::bitset<N> &src);        // <6>
```
1. Overwrites the bit-vector with the bits from a single word `src`, which is some unsigned integer type.
2. Overwrites the bit-vector with the bits from an iteration where the `value_type` of the iterator is some unsigned integer type.
3. Overwrites the bit-vector with the bits from an initializer-style list of unsigned integers.
4. Overwrites the bit-vector with the bits from a vector of unsigned integers.
5. Overwrites the bit-vector with the bits from a fixed array of unsigned integers.
6. Overwrites the bit-vector with the bits from a `std::bitset`.

::: {.callout-note}
# These resize the destination
These functions all resize the destination bit-vector to make it absorb all the source bits.
:::

## Template Parameters

Parameter   | Description
---------   | -----------
`Src`       | The type of unsigned integers whose bits will fill the destination bit-vector. There is _no_ requirement that `Src` and `Block` are the same. For example, we can add the bits from a list of 32-bit unsigned integers while the storage scheme for the bit-vector remains the default 64-bit type.
`Iter`      | An iterator --- might be the type returned by `std::cbegin(collection)` and `std::cend(collection)`. The `Iter::value_type` should be some unsigned integer type, but it need not match the `Block` type.
: {.bordered .hover .responsive tbl-colwidths="[10,90]"}

[Example --- Overwriting a bit-vector with the bits from unsigned words]{.bt}
```cpp
#include <bit/bit.h>
int main()
{
    bit::vector v;                                      // <1>
    std::cout << "v: " << v << '\n';
    v.set_to(std::uint8_t(0));                          // <2>
    std::cout << "v: " << v << '\n';
    v.set_to({std::uint8_t(255), std::uint8_t(0)});     // <3>
    std::cout << "v: " << v << '\n';
    std::vector<std::uint8_t> vec{255, 0};              // <4>
    v.set_to(vec);
    std::cout << "v: " << v << '\n';
    v.set_to(vec.cbegin(), vec.cend());                 // <5>
    std::cout << "v: " << v << '\n';
    std::bitset<8> bs(255);                             // <6>
    v.set_to(bs);
    std::cout << "v: " << v << '\n';
}
```
1. Default constructor makes an empty vector.
2. Fills with eight 0-bits.
3. Fill with a list of eight 1-bits and eight 0-bits.
4. Fills with a `std::vector` with eight 1-bits and eight 0-bits.
5. Fills with a `std::vector` with eight 1-bits and eight 0-bits using the usual iterators.
6. Fills with a `std::bitset` with eight 1-bits.

[Output]{.bt}
```bash
v: []
v: [0 0 0 0 0 0 0 0]
v: [1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
v: [1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
v: [1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
v: [1 1 1 1 1 1 1 1]
```

### See Also
[`vector::append`]      \
[`vector::export_to`]   \
[`vector::export_all_to`]
