# Metadata for this documentation project.
# This version just puts up a minimal "this site is deprecated" page.
project:
    type: website
    output-dir: _site

format:
    html:
        theme:
          - cosmo
          - assets/css/theme.scss

website:
    title: "Bit Space/GF(2)"
    google-analytics: G-G40Q4SR3K4
    site-url: "https://nessan.github.io/bit"
    repo-url: "https://github.com/nessan/bit"
    repo-subdir: docs

editor:
    markdown:
        canonical: true
